**Import Dependencies**

In [10]:
from __future__ import print_function
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree
import warnings
warnings.filterwarnings('ignore')

In [11]:
#pandas data frame
df = pd.read_csv('Crop_recommendation.csv')

In [12]:
#To show first five rows in the dataset
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [13]:
#no.of rows & coloumns
df.shape

(18667, 8)

In [14]:
#unique labels
df['label'].unique()

array(['rice', 'maize', 'Soyabeans', 'beans', 'peas', 'groundnuts',
       'cowpeas', 'banana', 'mango', 'grapes', 'watermelon', 'apple',
       'orange', 'cotton', 'coffee'], dtype=object)

In [15]:
#count of labels
df['label'].value_counts()

label
rice          1529
Soyabeans     1430
banana        1430
beans         1375
cowpeas       1342
orange        1342
maize         1309
coffee        1210
peas          1100
groundnuts    1100
mango         1100
grapes        1100
watermelon    1100
apple         1100
cotton        1100
Name: count, dtype: int64

In [16]:
#heat map
#sns.heatmap(df.corr(),annot=True)

In [17]:
#Dividing the X_dataset and y_dataset
features = df[['N', 'P','K','temperature', 'humidity', 'ph', 'rainfall']]
target = df['label']
labels = df['label']

In [18]:
# Initialzing empty lists to append all model's name and corresponding name
acc = []
model = []

In [19]:
# Splitting into train and test data

from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(features,target,test_size = 0.2,random_state =2)

In [20]:
#Import cross validation score
from sklearn.model_selection import cross_val_score

**Decision Tree**

In [21]:
from sklearn.tree import DecisionTreeClassifier

DecisionTree = DecisionTreeClassifier(criterion="entropy",random_state=2,max_depth=5)

DecisionTree.fit(Xtrain,Ytrain)

predicted_values = DecisionTree.predict(Xtest)
x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('Decision Tree')
print("DecisionTrees's Accuracy is: ", x*100)

print(classification_report(Ytest,predicted_values))

DecisionTrees's Accuracy is:  99.97321906802357
              precision    recall  f1-score   support

   Soyabeans       1.00      1.00      1.00       294
       apple       1.00      1.00      1.00       212
      banana       1.00      1.00      1.00       284
       beans       1.00      1.00      1.00       260
      coffee       1.00      1.00      1.00       233
      cotton       1.00      1.00      1.00       212
     cowpeas       1.00      1.00      1.00       252
      grapes       1.00      1.00      1.00       226
  groundnuts       1.00      1.00      1.00       216
       maize       1.00      1.00      1.00       277
       mango       1.00      1.00      1.00       213
      orange       1.00      1.00      1.00       293
        peas       1.00      1.00      1.00       219
        rice       1.00      1.00      1.00       314
  watermelon       1.00      1.00      1.00       229

    accuracy                           1.00      3734
   macro avg       1.00      1.0

In [22]:
# Cross validation score (Decision Tree)
score = cross_val_score(DecisionTree, features, target,cv=5)

score

In [23]:
import pickle
DT_pkl_filename = 'models/DecisionTree.pkl'
# Open the file to save as pkl file
DT_Model_pkl = open(DT_pkl_filename, 'wb')
pickle.dump(DecisionTree, DT_Model_pkl)
# Close the pickle instances
DT_Model_pkl.close()

**Gaussian Naive Bayes**

In [24]:
from sklearn.naive_bayes import GaussianNB

NaiveBayes = GaussianNB()

NaiveBayes.fit(Xtrain,Ytrain)

predicted_values = NaiveBayes.predict(Xtest)
x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('Naive Bayes')
print("Naive Bayes's Accuracy is: ", x)

print(classification_report(Ytest,predicted_values))

Naive Bayes's Accuracy is:  0.9997321906802357
              precision    recall  f1-score   support

   Soyabeans       1.00      1.00      1.00       294
       apple       1.00      1.00      1.00       212
      banana       1.00      1.00      1.00       284
       beans       1.00      1.00      1.00       260
      coffee       1.00      1.00      1.00       233
      cotton       1.00      1.00      1.00       212
     cowpeas       1.00      1.00      1.00       252
      grapes       1.00      1.00      1.00       226
  groundnuts       1.00      1.00      1.00       216
       maize       1.00      1.00      1.00       277
       mango       1.00      1.00      1.00       213
      orange       1.00      1.00      1.00       293
        peas       1.00      1.00      1.00       219
        rice       1.00      1.00      1.00       314
  watermelon       1.00      1.00      1.00       229

    accuracy                           1.00      3734
   macro avg       1.00      1.00

In [25]:
# Cross validation score (NaiveBayes)
score = cross_val_score(NaiveBayes,features,target,cv=5)
score

array([0.99946438, 0.99598286, 0.99919636, 1.        , 0.99517814])

In [26]:
import pickle
NB_pkl_filename = 'models/NBClassifier.pkl'
# Open the file to save as pkl file
NB_Model_pkl = open(NB_pkl_filename, 'wb')
pickle.dump(NaiveBayes, NB_Model_pkl)
# Close the pickle instances
NB_Model_pkl.close()

**Support Vector Classification**

In [27]:
from sklearn.svm import SVC
# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler
# fit scaler on training data
norm = MinMaxScaler().fit(Xtrain)
X_train_norm = norm.transform(Xtrain)
# transform testing dataabs
X_test_norm = norm.transform(Xtest)
SVM = SVC(kernel='poly', degree=3, C=1)
SVM.fit(X_train_norm,Ytrain)
predicted_values = SVM.predict(X_test_norm)
x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('SVM')
print("SVM's Accuracy is: ", x)

print(classification_report(Ytest,predicted_values))

SVM's Accuracy is:  1.0
              precision    recall  f1-score   support

   Soyabeans       1.00      1.00      1.00       294
       apple       1.00      1.00      1.00       212
      banana       1.00      1.00      1.00       284
       beans       1.00      1.00      1.00       260
      coffee       1.00      1.00      1.00       233
      cotton       1.00      1.00      1.00       212
     cowpeas       1.00      1.00      1.00       252
      grapes       1.00      1.00      1.00       226
  groundnuts       1.00      1.00      1.00       216
       maize       1.00      1.00      1.00       277
       mango       1.00      1.00      1.00       213
      orange       1.00      1.00      1.00       293
        peas       1.00      1.00      1.00       219
        rice       1.00      1.00      1.00       314
  watermelon       1.00      1.00      1.00       229

    accuracy                           1.00      3734
   macro avg       1.00      1.00      1.00      3734
we

In [28]:
# Cross validation score (SVM)
score = cross_val_score(SVM,features,target,cv=5)
score

array([0.99973219, 0.99223353, 0.99812483, 1.        , 1.        ])

In [29]:
import pickle
SVM_pkl_filename = 'models/SVMClassifier.pkl'
# Open the file to save as pkl file
SVM_Model_pkl = open(SVM_pkl_filename, 'wb')
pickle.dump(SVM, SVM_Model_pkl)
# Close the pickle instances
SVM_Model_pkl.close()

**Logistic Regression**

In [30]:
from sklearn.linear_model import LogisticRegression

LogReg = LogisticRegression(random_state=2)

LogReg.fit(Xtrain,Ytrain)

predicted_values = LogReg.predict(Xtest)

x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('Logistic Regression')
print("Logistic Regression's Accuracy is: ", x)

print(classification_report(Ytest,predicted_values))

Logistic Regression's Accuracy is:  0.9919657204070702
              precision    recall  f1-score   support

   Soyabeans       1.00      1.00      1.00       294
       apple       1.00      1.00      1.00       212
      banana       1.00      1.00      1.00       284
       beans       1.00      1.00      1.00       260
      coffee       1.00      1.00      1.00       233
      cotton       0.93      0.92      0.93       212
     cowpeas       1.00      1.00      1.00       252
      grapes       1.00      1.00      1.00       226
  groundnuts       1.00      1.00      1.00       216
       maize       0.94      0.95      0.95       277
       mango       1.00      1.00      1.00       213
      orange       1.00      1.00      1.00       293
        peas       1.00      1.00      1.00       219
        rice       1.00      1.00      1.00       314
  watermelon       1.00      1.00      1.00       229

    accuracy                           0.99      3734
   macro avg       0.99  

In [31]:
# Cross validation score (Logistic Regression)
score = cross_val_score(LogReg,features,target,cv=5)
score

array([0.98607392, 0.98928763, 0.99089204, 0.988749  , 0.98607018])

In [32]:
import pickle
LR_pkl_filename = 'models/LogisticRegression.pkl'
# Open the file to save as pkl file
LR_Model_pkl = open(DT_pkl_filename, 'wb')
pickle.dump(LogReg, LR_Model_pkl)
# Close the pickle instances
LR_Model_pkl.close()

**Random Forest**

In [33]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=20, random_state=0)
RF.fit(Xtrain,Ytrain)

predicted_values = RF.predict(Xtest)

x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('RF')
print("RF's Accuracy is: ", x)

print(classification_report(Ytest,predicted_values))

RF's Accuracy is:  0.9997321906802357
              precision    recall  f1-score   support

   Soyabeans       1.00      1.00      1.00       294
       apple       1.00      1.00      1.00       212
      banana       1.00      1.00      1.00       284
       beans       1.00      1.00      1.00       260
      coffee       1.00      1.00      1.00       233
      cotton       1.00      1.00      1.00       212
     cowpeas       1.00      1.00      1.00       252
      grapes       1.00      1.00      1.00       226
  groundnuts       1.00      1.00      1.00       216
       maize       1.00      1.00      1.00       277
       mango       1.00      1.00      1.00       213
      orange       1.00      1.00      1.00       293
        peas       1.00      1.00      1.00       219
        rice       1.00      1.00      1.00       314
  watermelon       1.00      1.00      1.00       229

    accuracy                           1.00      3734
   macro avg       1.00      1.00      1.0

In [34]:
# Cross validation score (Random Forest)
score = cross_val_score(RF,features,target,cv=5)
score

array([1.        , 0.99946438, 1.        , 0.99919636, 1.        ])

In [35]:
import pickle
RF_pkl_filename = 'models/RandomForest.pkl'
# Open the file to save as pkl file
RF_Model_pkl = open(RF_pkl_filename, 'wb')
pickle.dump(RF, RF_Model_pkl)
# Close the pickle instances
RF_Model_pkl.close()

**XGBoost**

In [36]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [51]:
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.metrics import classification_report
import xgboost as xgb
import numpy as np

# Assuming you've already defined and split your data into Xtrain, Xtest, Ytrain, Ytest

# Initialize the label encoder
label_encoder = LabelEncoder()

# Fit label encoder and transform the target variable
Ytrain_encoded = label_encoder.fit_transform(Ytrain)
Ytest_encoded = label_encoder.transform(Ytest)

# Train the XGBoost classifier
XB = xgb.XGBClassifier()
XB.fit(Xtrain, Ytrain_encoded)

# Predict using the trained classifier
predicted_values = XB.predict(Xtest)

# Calculate accuracy
accuracy = metrics.accuracy_score(Ytest_encoded, predicted_values)
print("XGBoost's Accuracy is:", accuracy)

# Append accuracy and model name to lists
acc.append(accuracy)
model.append('XGBoost')

# Print classification report
print(classification_report(Ytest_encoded, predicted_values, target_names=label_encoder.classes_))





XGBoost's Accuracy is: 1.0
              precision    recall  f1-score   support

   Soyabeans       1.00      1.00      1.00       294
       apple       1.00      1.00      1.00       212
      banana       1.00      1.00      1.00       284
       beans       1.00      1.00      1.00       260
      coffee       1.00      1.00      1.00       233
      cotton       1.00      1.00      1.00       212
     cowpeas       1.00      1.00      1.00       252
      grapes       1.00      1.00      1.00       226
  groundnuts       1.00      1.00      1.00       216
       maize       1.00      1.00      1.00       277
       mango       1.00      1.00      1.00       213
      orange       1.00      1.00      1.00       293
        peas       1.00      1.00      1.00       219
        rice       1.00      1.00      1.00       314
  watermelon       1.00      1.00      1.00       229

    accuracy                           1.00      3734
   macro avg       1.00      1.00      1.00      3734

In [38]:
import pickle
XB_pkl_filename = 'models/XGBoost.pkl'
# Open the file to save as pkl file
XB_Model_pkl = open(XB_pkl_filename, 'wb')
pickle.dump(XB, XB_Model_pkl)
# Close the pickle instances
XB_Model_pkl.close()

**Accuracy Comparison**

In [39]:
plt.figure(figsize=[10,5],dpi = 100)
plt.title('Accuracy Comparison')
plt.xlabel('Accuracy')
plt.ylabel('Algorithm')
sns.barplot(x = acc,y = model,palette='dark')

NameError: name 'plt' is not defined

In [40]:
accuracy_models = dict(zip(model, acc))
for k, v in accuracy_models.items():
    print (k, '-->', v)

Decision Tree --> 0.9997321906802357
Naive Bayes --> 0.9997321906802357
SVM --> 1.0
Logistic Regression --> 0.9919657204070702
RF --> 0.9997321906802357
XGBoost --> 1.0


**Predictions**

In [52]:
data = np.array([[104, 18, 30, 23.603016, 60.3, 6.7, 140.91]])
predicted_label_encoded = XB.predict(data)
predicted_label = label_encoder.inverse_transform(predicted_label_encoded)
print(predicted_label)

['coffee']


In [53]:
data = np.array([[83, 41, 43, 21.0525355, 82.67839517, 6.254028451, 233.1075816
]])
prediction = RF.predict(data)
print(prediction)

['rice']
